build:
    environment:
        php:
            version: 7.2.11
        mysql: false
        postgresql: false
        redis: false

    cache:
        directories: [vendor/]

    dependencies:
        before:
        - command: composer install --no-interaction

    nodes:
        analysis:
            tests:
                override:
                - php-scrutinizer-run
        test-and-coverage:
            tests:
                override:
                -
                    command: phpdbg -qrr app/vendor/bin/phpunit --coverage-clover coverage/clover.xml
                    coverage:
                        file: coverage/clover.xml
                        format: clover

filter:
    paths: [src/*]
    excluded_paths: [tests/*, vendor/*]

checks:
    php: true